permalink: /posts/:title
relative_permalinks: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title: Sugar
production_url: http://sugar-framework.github.io
description: "Web framework for Elixir, built on top of Plug"
analytics: UA-43025826-6
author:
  github: sugar-framework
  twitter: sugar_framework
